name: Cypress Tests and deployment
on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  cypress-run:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Linter and Prettier
        run: |
          npx eslint --quiet
          npx prettier --check .

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: false

      - name: Upload Cypress results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-results
          path: cypress/results
          retention-days: 30

      - name: Deploy results to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: cypress/results
